// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webforms.DataLayer;

namespace webforms.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250201125246_Flights-Schema-With-Data")]
    partial class FlightsSchemaWithData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webforms.Models.FlightRm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Airline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArrivalId")
                        .HasColumnType("int");

                    b.Property<int>("DepartureId")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingNumberOfSeats")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalId");

                    b.HasIndex("DepartureId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Airline = "American Airlines",
                            ArrivalId = 2,
                            DepartureId = 1,
                            Price = "3543",
                            RemainingNumberOfSeats = 653
                        },
                        new
                        {
                            Id = 2,
                            Airline = "Deutsche BA",
                            ArrivalId = 4,
                            DepartureId = 3,
                            Price = "2027",
                            RemainingNumberOfSeats = 743
                        },
                        new
                        {
                            Id = 3,
                            Airline = "British Airways",
                            ArrivalId = 6,
                            DepartureId = 5,
                            Price = "2351",
                            RemainingNumberOfSeats = 240
                        },
                        new
                        {
                            Id = 4,
                            Airline = "Basiq Air",
                            ArrivalId = 8,
                            DepartureId = 7,
                            Price = "2207",
                            RemainingNumberOfSeats = 459
                        },
                        new
                        {
                            Id = 5,
                            Airline = "BB Heliag",
                            ArrivalId = 10,
                            DepartureId = 9,
                            Price = "1098",
                            RemainingNumberOfSeats = 331
                        });
                });

            modelBuilder.Entity("webforms.Models.TimePlaceRm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Timeplaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Place = "Los Angeles",
                            Time = new DateTime(2025, 2, 1, 14, 52, 46, 383, DateTimeKind.Local).AddTicks(3017)
                        },
                        new
                        {
                            Id = 2,
                            Place = "Istanbul",
                            Time = new DateTime(2025, 2, 1, 21, 52, 46, 384, DateTimeKind.Local).AddTicks(3004)
                        },
                        new
                        {
                            Id = 3,
                            Place = "Munchen",
                            Time = new DateTime(2025, 2, 1, 17, 52, 46, 384, DateTimeKind.Local).AddTicks(3004)
                        },
                        new
                        {
                            Id = 4,
                            Place = "Schiphol",
                            Time = new DateTime(2025, 2, 1, 19, 52, 46, 384, DateTimeKind.Local).AddTicks(3004)
                        },
                        new
                        {
                            Id = 5,
                            Place = "London, England",
                            Time = new DateTime(2025, 2, 1, 23, 52, 46, 384, DateTimeKind.Local).AddTicks(3004)
                        },
                        new
                        {
                            Id = 6,
                            Place = "Vizzola-Ticino",
                            Time = new DateTime(2025, 2, 2, 3, 52, 46, 384, DateTimeKind.Local).AddTicks(3004)
                        },
                        new
                        {
                            Id = 7,
                            Place = "Amsterdam",
                            Time = new DateTime(2025, 2, 2, 9, 52, 46, 384, DateTimeKind.Local).AddTicks(3004)
                        },
                        new
                        {
                            Id = 8,
                            Place = "Glasgow, Scotland",
                            Time = new DateTime(2025, 2, 2, 4, 52, 46, 384, DateTimeKind.Local).AddTicks(3004)
                        },
                        new
                        {
                            Id = 9,
                            Place = "Zurich",
                            Time = new DateTime(2025, 2, 2, 2, 52, 46, 384, DateTimeKind.Local).AddTicks(3004)
                        },
                        new
                        {
                            Id = 10,
                            Place = "Baku",
                            Time = new DateTime(2025, 2, 2, 9, 52, 46, 384, DateTimeKind.Local).AddTicks(3004)
                        });
                });

            modelBuilder.Entity("webforms.Models.FlightRm", b =>
                {
                    b.HasOne("webforms.Models.TimePlaceRm", "Arrival")
                        .WithMany()
                        .HasForeignKey("ArrivalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("webforms.Models.TimePlaceRm", "Departure")
                        .WithMany()
                        .HasForeignKey("DepartureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
